//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.WCFInventario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFInventario.IInvService")]
    public interface IInvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/AddItem", ReplyAction="http://tempuri.org/IInvService/AddItemResponse")]
        void AddItem(DTO.Almacen item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/AddItem", ReplyAction="http://tempuri.org/IInvService/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(DTO.Almacen item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/GetItem", ReplyAction="http://tempuri.org/IInvService/GetItemResponse")]
        DTO.Almacen GetItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/GetItem", ReplyAction="http://tempuri.org/IInvService/GetItemResponse")]
        System.Threading.Tasks.Task<DTO.Almacen> GetItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/GetAll", ReplyAction="http://tempuri.org/IInvService/GetAllResponse")]
        System.Collections.Generic.List<DTO.Almacen> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvService/GetAll", ReplyAction="http://tempuri.org/IInvService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTO.Almacen>> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvServiceChannel : MVC.WCFInventario.IInvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvServiceClient : System.ServiceModel.ClientBase<MVC.WCFInventario.IInvService>, MVC.WCFInventario.IInvService {
        
        public InvServiceClient() {
        }
        
        public InvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddItem(DTO.Almacen item) {
            base.Channel.AddItem(item);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(DTO.Almacen item) {
            return base.Channel.AddItemAsync(item);
        }
        
        public DTO.Almacen GetItem(int id) {
            return base.Channel.GetItem(id);
        }
        
        public System.Threading.Tasks.Task<DTO.Almacen> GetItemAsync(int id) {
            return base.Channel.GetItemAsync(id);
        }
        
        public System.Collections.Generic.List<DTO.Almacen> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTO.Almacen>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
